version: "3.8"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: labo-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      kevin-network:
  back:
    build: ./back
    container_name: labo-back
    environment:
      - VIRTUAL_HOST=api.server1.net
      - VIRTUAL_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - nginx
    networks:
      kevin-network:
  labo:
    build: ./labo
    container_name: labo-queries
    environment:
      - VIRTUAL_HOST=labo.net
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"
    networks:
      kevin-network:
networks:
  kevin-network:
