version: "3.8"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: labo-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      kevin-network:
  labo:
    build: ./labo
    container_name: labo-queries
    environment:
      - REDIS_SERVER_IP=redis-server
      - VIRTUAL_HOST=labo.net
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"
    networks:
      kevin-network:
networks:
  kevin-network:
